### ISSUE TITLE
Player-InvitePlayer-PlayTogether

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#100]
**Story:** As a logged-in user who have already been in a game room, he/she can invite other logged-in users to player together. 

**Acceptance Criteria:**
- [ ] In the “waiting area” page, a progress bar is shown to all users who have already joined the game room, which tells what percentage of players have been in the room. 
- [ ] In the waiting page, there is a “invite online players” area which lists pairs of online friend’s username and a “invite” button. 
- [ ] By clicking on the “invite” button, the users (both owner of the game room and other players) who have already been in a game room, they can send invitations to online friends to enter this game room. 
- [ ] A logged-in user who receives invitation to a game room will see the invitation in the “Notification” page.  
- [ ] There is a “accept” button and a “ignore” button near each invitation in the “Notification” page. 
- [ ] If the user clicks “accept” to accept the invitation, he will be redirected to the “waiting area” page.  This invitation request is processed in the backend. 
- [ ] After a user accepts invitation and join the game room, the progress bar is updated. 
- [ ] If the user clicks “ignore” button, he will stay in the notification page.  This invitation request is processed in the backend. 
- [ ] When the game room is full of players, they cannot invite other logged-in users.  
- [ ] When the game room is full of players, the progress bar is updated as 100 percent. 
- [ ] There is a “start” button shown in the “waiting” page for the room owner. The game room owner can click “start” button to start the game. 

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#51
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#52
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#53
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#54
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#55
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#56
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#57

**Comment by runzeliuzh** [comment]
add a list of friends on the waiting page to invite friends to join the game: https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-client/commit/b604db57a33f3dcec2358ae8342f115c03f81b45

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-client/commit/7f5768b7af7f2c9004e1c1378da4fa0d2260e023
