### ISSUE TITLE
User-SearchPlayer-SendInvitation

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#101]
**Story:** As a logged-in user, I want to add players as friends by searching for usernames and sending invitations to them. 

**Acceptance Criteria:**
- [ ] In the "Friends " page, a search box is displayed which allows a logged-in user to enter usernames. 
- [ ] If there is a registered user whose username is exactly the input username, the search result will be displayed in a dropdown box.  
- [ ] If a registered user with this username can be found, "Send Request" button is enabled, and the user can send an invitation to that player. 
- [ ] If there is no registered user with this username, the search result (displayed in the dropdown box) is empty. Indicating that no user exists with the input username. The " Send Request" button is disabled. 
- [ ] If a registered user with the input username can be found, but he is already a friend. The " Send Request" button is disabled. 
- [ ] The user who receives a friend request can see this invitation on the Notification page.  
- [ ] There is a “accept” button and a “ignore” button near the friend invitation in the Notification page.  
- [ ] The user who receives the friend request can click the “accept” button to accept the friend request. Upon approval, the user is added to the friends list of whom sends the friend request. 
- [ ] The user who receives the friend request can click the “ignore” button to reject the friend request. 
- [ ] Upon rejection, the user who sends the friend request cannot see this user in his friend list.

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#35
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#59
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#36
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#37
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#62
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#38
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#64
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#65
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#39
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#67

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-server/commit/d929cc33767b972fcf33ba7523f687a805d20893
