### ISSUE TITLE
GuessingPlayer-SeePainting-EnterAnswer

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#11]
**Story:** As a guessing player, I want to see the painting and have some time to think of the answer. 

**Acceptance Criteria:**
- [ ] After the guessing phase begins, there is a timer which begins to count down.  
- [ ] There is a white board which displays the painting during the guessing phase. No one can edit the painting. 
- [ ] There is a text field for guessing players to enter answers. Within the pre-set time, the user is free to try different inputs. 

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#42
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#69
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#43
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#44

**Comment by GY-Meng** [comment]
submit the painting result to the guessing stage
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-client/commit/14fa582d3003519284784154b3dd413e1d299c06

**Comment by runzeliuzh** [comment]
Image saving. https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-server/commit/05b079b05d639d6a1a01c6c8ce9a93642c8040c9
