### ISSUE TITLE
DrawingPlayer-Erase-ModifyPainting

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#13]
**Story:** As a drawing player, I want to use eraser to modify the painting. 

**Acceptance Criteria:**
- [ ] During the drawing phase, there is an eraser icon in the white board area. The guessing player can click it to use the eraser. 
- [ ] When the drawing player uses eraser in a certain area on the white board, the area turns white. 
- [ ] The left area remains as it is and is preserved on the whiteboard. 
- [ ] The drawing player can switch to use the pen tool by clicking the pen icon. 

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#49
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#50
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#51

**Priority:** middle 
**Estimate:** 10h

**Comment by GY-Meng** [comment]
ad4efbbfbd2db2f701afe6de3d4a15ba6fb55357
