### ISSUE TITLE
GuessingPlayer-SeeRank-KnowScore

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#15]
**Story:** As a guessing player, I want to see the rank of final scores of all players obtained in this round. 

**Acceptance Criteria:**
- [ ] In one round, which includes 2 or 4 turns (depending on the game mode), after each turn, the score rank page will be updated on the screen. 
- [ ]  After a round ends, a final score page is displayed showing all players’ scores earned in this round and the rank. The order of players depends on the scores obtained in this round (from highest to lowest). 
- [ ] There is a “Exit” button on the final score page. Players can click the “Exit” button to leave the game room. The players can only exit the game room after this round ends. 
- [ ] The score earned in this round is added to the total score in the user profile. 
- [ ] The score earned in this round is compared with the previous records. If the score earned in this round is higher than all previous records, this score becomes the highest score. 
- [ ] Upon total score changes or best score changes, the user profile is updated. 

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#52
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#53
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#54
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#55
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#85
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#86
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#87

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-server/commit/a4040b149b32f758b41988a6a6c37b61ac4c3ef2
