### ISSUE TITLE
User-Login-HomePage

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#94]
**Story:** As a registered user, I want to log in with my username and password in order to see my profile and play the game. 

**Acceptance Criteria:**
- [ ] There is a form which allows users to enter their username and password in the login page. 
- [ ] There is a "login" button on the home page. 
- [ ] Users can enter their username and password on the login page, click the "login" button to login. 
- [ ] If a user enters the correct username and password, he will be redirected to the game lobby page (home page). 
- [ ] In the game lobby page headers, there is a navigation menu containing “Profile”. By clicking the “profile” button in the navigation menu, the user is redirected to his Profile page.
- [ ] Profile page shows their username, password (hidden), total score, best score in a round. 
- [ ] If the username or password is wrong, an error is displayed, and the user will be redirected to the login page. 
- [ ] If a user is not logged in, he cannot see game lobby, create/join a game or see friends/notifications/profiles.
- [ ] Logged in users can log out using the "logout" button on the page headers. 
- [ ] After a user click the logout button, he will be redirected to the login page.

**Development Tasks:**
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#3
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#4
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#15
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#16
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#23
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#22
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#21
