### ISSUE TITLE
User-EditProfile-Update

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#95]
**Story:** As a logged-in user, I want to edit my user profile such as username and password, to update my personal information and secure my account.

**Acceptance Criteria:**
 - [ ] By clicking on an “edit” button in the user profile page, the user is able to change username and password. 
 - [ ] The profile editing page is only accessible for logged-in users. Logged-in users can only change their own profile. 
 - [ ] The user can only change to a username which has not been used by other users. Upon failure, an error is displayed, and the user can continue to input their intended username.  After changing and saving the username, the user is redirected to the profile page and the updated username is displayed. 
 - [ ] When changing password, the user must type the actual(original) password and type the new password. If user inputs wrong original password, an error is displayed. If the new password is the same as the original password, an error is displayed, and the user is required to input another one. After changing password, the user is redirected to the login page and has to login with new credentials.
 - [ ] If the user cancels the editing, the user is redirected to the profile page and the original profile is displayed. 

**Development Tasks:**
 - [x] sopra-fs23-group-19/sopra-fs23-group-19-client#17
 - [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#18
 - [x] sopra-fs23-group-19/sopra-fs23-group-19-server#30
 - [x] sopra-fs23-group-19/sopra-fs23-group-19-server#31
 - [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#19

**Comment by runzeliuzh** [comment]
We don't plan to do this "After changing password, the user is redirected to the login page and has to login with new credentials."

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-client/commit/c3a15030dbc1aa861de3e1d26a3a036c00c16792

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-server/commit/a618acaa434397c97d26f03f77dbf28e3cd72880
