### ISSUE TITLE
User-SeeProfile-SeeScore

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#96]
**Story:** As a logged-in user, I want to see my score in the profile page and see my friend's score in their profile page. 

**Acceptance Criteria:**
- [ ] Upon log in, in the page header there is a navigation menu containing a “Friends” button.
- [ ] By clicking on the “Friends” button, the user is redirected to the “Friends” page. 
- [ ] In the "Friends" page, a logged-in user can view a list of his/her friends and select one for viewing profile.  
- [ ] By clicking on a username, the user is redirected to a profile page of that user. 
- [ ] The profile page contains the following data: username, total score, best score won in a round, online status. 
- [ ] The "Friends" page and profile page are only accessible for logged-in users. 

**Development Tasks:**
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#20
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#21
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#22
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#36
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#37

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-server/commit/97a92fcb73fd618ec779d5cd06239e1ab2f8b8e0

**Comment by runzeliuzh** [comment]
Friend overview page https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-client/commit/31e27894136b7f5e13a062232ac394f373907fbb
