### ISSUE TITLE
GuessingPlayer-GuessOneWord-AnswerSaved

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#99]
**Story:** As a guessing player, I want to guess only once each turn within the time limitation, the correct answer should be only one word. 

**Acceptance Criteria:**
- [ ] There is a button to submit the answer. 
- [ ] In each turn, each player only has one opportunity to guess, after submitting answers, they cannot change their answers. 
- [ ] When a user starts guessing, there is a 1-minute timer. Within this preset time, a guessing player can click “submit” button to submit the answer.
- [ ] If the time is out, the user doesn’t complete his/her answer, he/she cannot continue entering, and the answer as it is will be submitted automatically. 
- [ ] If the time is out, the player hasn’t entered a word, empty result will be submitted. 
- [ ] After the answer has been submitted, the answers will be sent back to backend for calculating the points each player may get. 

**Development Tasks:**
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#29
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#30
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#48
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-client#31
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#50

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-server/commit/692c2004085f6964b6ec94db619647de031aeb4d
